// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkyycdseogwsgatxygtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZreXljZHNlb2d3c2dhdHh5Z3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDc5MzYsImV4cCI6MjA2ODQ4MzkzNn0.mnGsqaiklA0Vk2El_Q0ie3Ubevn4cHd4K_45S6WDl44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});