// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aesypvthycthlujjuhfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlc3lwdnRoeWN0aGx1amp1aGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NjE2NDEsImV4cCI6MjA1NjUzNzY0MX0.A7r6H7CZcmbpg9SwhK7XyQCiDcUYW55D0AX3HKuT588";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);