// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcpussumksywsjwydruq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcHVzc3Vta3N5d3Nqd3lkcnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1Mzg0NjQsImV4cCI6MjA3NzExNDQ2NH0.F-4eNfb7-U2Jf3vyNOTGRAoO5oRfdIbmnlB5xl1lpME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});